# My Coding Notebook and Practices

## REGEX = Regular Expression

### Shorthand Codes for Common Character Classes

| Shorthand | Matches |
| --- | --- |
| `\d` | Any digit, `0` to `9` |
| `\D` | Any character that is **not** a digit |
| `\w` | Any letter, digit, or underscore ("word" character) |
| `\W` | Any character that is **not** a letter, digit, or underscore |
| `\s` | Any space, tab, or newline ("whitespace") |
| `\S` | Any character that is **not** a space, tab, or newline |
| `\b` | A word boundary (position between `\w` and `\W`) |
| `.` | Any character **except** a newline (use `re.DOTALL` to include newlines) |

**Making your own character classes**

| Pattern | Matches |
| --- | --- |
| `[aeiouAEIOU]` | Any one vowel |
| `[a-zA-Z0-9]` | Any one letter or digit (ranges with `-`) |
| `[^aeiouAEIOU]` | *Negative* class — any character that is **not** a vowel |
| `[0-5.]` | Digits 0-5 or a literal period (most symbols need no escaping inside `[]`) |

**Anchors and quantifiers (quick reference)**

| Pattern | Meaning |
| --- | --- |
| `^spam` | String must **begin** with `spam` |
| `spam$` | String must **end** with `spam` |
| `?` | Zero or one of the preceding group |
| `*` | Zero or more of the preceding group |
| `+` | One or more of the preceding group |
| `{n}` / `{n,}` / `{n,m}` | Exactly n / n or more / between n and m |
| `{n,m}?` `*?` `+?` | Non-greedy (shortest) match instead of greedy (longest) |

> Always write regex patterns as raw strings — `r'\d{3}'` — so Python doesn't consume the backslashes.

In [1]:
import re

In [3]:
phoneNumRegex = re.compile(r'\d{3}-\d{3}-\d{4}')
mo = phoneNumRegex.search('My number is 415-555-4242.')
print('Phone number found: ' + mo.group())

Phone number found: 415-555-4242

In [20]:
# Grouping with Parentheses
# Function to extract a specific group from a phone number string returns the requested group
def isPhoneNumber(number, group):
    phoneNumRegexpattern = re.compile(r'(\d{3})-(\d{3}-\d{4})')
    mo = phoneNumRegexpattern.search(number)
    return mo.group(group)

In [21]:
# Function to extract area code and main number from a phone number string returns a tuple containing the area code and main number
def isPhoneNumber(number):
    phoneNumRegexpattern = re.compile(r'(\d{3})-(\d{3}-\d{4})')
    mo = phoneNumRegexpattern.search(number)
    return mo.groups()

In [18]:
isPhoneNumber('My number is 415-555-4242.', 1)  # Returns '415'

'415'

In [19]:
isPhoneNumber('My number is 415-555-4242.', 2)  # Returns '555-4242'

'555-4242'

In [15]:
areacode, mainNumber = isPhoneNumber('My number is 415-555-4242.')
print('Area code: ' + areacode)
print('Main number: ' + mainNumber)

Area code: 415
Main number: 555-4242

In [4]:
# Matching Multiple Groups with the Pipe
heroRegex = re.compile(r'Batman|Tina Fey')
mo1 = heroRegex.search('Batman and Tina Fey.')
print(mo1.group())

Batman

In [5]:
mo2 = heroRegex.search('Tina Fey and Batman.')
print(mo2.group())

Tina Fey

In [7]:
# Pipe to match one of several patterns as part of the regex
batRegex = re.compile(r'Bat(man|mobile|copter|bat)')
mo = batRegex.search('Batmobile lost a wheel')
print(mo.group())
print(mo.group(1))

Batmobile
mobile

In [9]:
# Optional Matching with the Question Mark
phoneRegex = re.compile(r'(\d\d\d-)?\d\d\d-\d\d\d\d')
mo1 = phoneRegex.search('My number is 415-555-4242')
print(mo1.group())

415-555-4242

In [12]:
mo2 = phoneRegex.search('My number is 555-4242')
print(mo2.group())

555-4242

In [10]:
batRegex = re.compile(r'Bat(wo)?man')
mo1 = batRegex.search('The Adventures of Batman')
print(mo1.group())

Batman

In [11]:
mo2 = batRegex.search('The Adventures of Batwoman')
print(mo2.group())

Batwoman

In [13]:
# Matching Zero or More with the Star
'''The *(called the star or asterisk) means "match zero or more -- the group that precedes the star can occur any number of times in the text'''
batRegex = re.compile(r'Bat(wo)*man')
mo1 = batRegex.search('The Adventures of Batman')
print(mo1.group())

Batman

In [14]:
mo2 = batRegex.search('The Adventures of Batwoman')
print(mo2.group())

Batwoman

In [15]:
mo3 = batRegex.search('The Adventures of Batwowowoman')
print(mo3.group())

Batwowowoman

In [17]:
# Matching One or More with the Plus 
batRegex = re.compile(r'Bat(wo)+man')
mo1 = batRegex.search('The Adventures of Batwoman')
print(mo1.group())

Batwoman

In [18]:
mo2 = batRegex.search('The Adventures of Batwowowoman')
print(mo2.group())

Batwowowoman

In [21]:
mo3 = batRegex.search('The Adventures of Batman')
mo3 == None
#print(mo3.group())

True

# Matching Specific Repaetitions with Curly Brackets

In [22]:
haRegex = re.compile(r'(Ha){3}')
mo4 = haRegex.search('HaHaHa')
print(mo4.group())

HaHaHa

In [23]:
mo2 = haRegex.search('Ha')
mo2 == None

True

## Greedy and Nongreedy Matching

In [24]:
# This section demonstrates the difference between greedy and non-greedy matching in regular expressions.
greedyHaRegex = re.compile(r'(Ha){3,5}')
mo1 = greedyHaRegex.search('HaHaHaHaHa')
print(mo1.group())

HaHaHaHaHa

In [25]:
nongreedyHaRegex = re.compile(r'(Ha){3,5}?')
mo2 = nongreedyHaRegex.search('HaHaHaHaHa')
print(mo2.group())

HaHaHa

In [27]:
# findall() Method
phoneNumRegex = re.compile(r'\d{3}-\d{3}-\d{4}')
mo = phoneNumRegex.search('Cell: 415-555-9999 Work: 212-555-0000')
print(mo)

<re.Match object; span=(6, 18), match='415-555-9999'>

In [28]:
# findall with no groups 
phoneNumRegex = re.compile(r'\d{3}-\d{3}-\d{4}')
mo = phoneNumRegex.findall('Cell: 415-555-9999 Work: 212-555-0000')
print(mo)

['415-555-9999', '212-555-0000']

In [29]:
# findall() with groups
phoneNumRegex = re.compile(r'(\d{3})-(\d{3})-(\d{4})')
mo = phoneNumRegex.findall('Cell: 415-555-9999 Work: 212-555-0000')
print(mo)

[('415', '555', '9999'), ('212', '555', '0000')]

## Regex Practice

In [2]:
# imports
import pandas as pd
import re
sample_contacts = pd.read_csv("/Users/courtneysmith/Documents/Projects/DataPractice/data/raw/sample_contacts.csv")

In [3]:
sample_contacts

               name                phone                       email
0      Alice Nguyen         415-555-4242    alice.nguyen@example.com
1         Bob Marsh       (212) 555-0198       bob.marsh@example.org
2        Carol Diaz           3125550147      carol_diaz@example.net
3     Dan Whitfield         415-555-1234       dan.whitfield@example
4     Erin Kowalski             555-8891   erin.kowalski@example.com
5         Frank Obi         206.555.7788      frank.obi@@example.com
6         Grace Lin      +1-503-555-0166     grace.lin@example.co.uk
7       Hank Petrov          503-55-0142      hankpetrov.example.com
8     Iris Calloway         617-555-3311   iris.calloway@example.com
9        Jamal Reed         617 555 2200     jamal.reed@example..com
10    Kira Sandoval         858-555-0113    kira.sandoval@example.io
11  Liam Fitzgerald  phone: 858-555-9021                @example.com
12    Maya Robinson         720-555-0175   maya.robinson@example.com
13   Noah Bergstrom         72-555-01755  noah.bergstrom@example.gov
14      Olivia Tran         919-555-6624     olivia.tran@example.com
15    Pedro Alvarez           919-555-88   pedro alvarez@example.com
16     Quinn Bailey         404-555-0190    quinn.bailey@example.com
17     Rosa Delgado         404/555/0132       rosa.delgado@example.
18   Sam Achterberg         208-555-7410  sam.achterberg@example.com
19     Tessa Moreau              2085550           tessa.moreau@.com

In [21]:
phoneNumRegex = re.compile(r'\d{3}-\d{3}-\d{4}')
correctly_formatted_ph_numbers = []
for phnum in sample_contacts['phone']:
    phone_matches =phoneNumRegex.fullmatch(phnum)
    if phone_matches:
        correctly_formatted_ph_numbers.append(phone_matches.group())

In [23]:
correctly_formatted_phone_number_matches = [
    phone_matches.group()
    for phnum in sample_contacts['phone']
    if (phone_matches := phoneNumRegex.fullmatch(phnum))
]

In [24]:
print(correctly_formatted_phone_number_matches)

['415-555-4242', '415-555-1234', '617-555-3311', '858-555-0113', '720-555-0175', '919-555-6624', '404-555-0190', '208-555-7410']

In [22]:
print(f'{len(correctly_formatted_ph_numbers)} of {len(sample_contacts)} phones are well formed')
print(correctly_formatted_ph_numbers)

8 of 20 phones are well formed
['415-555-4242', '415-555-1234', '617-555-3311', '858-555-0113', '720-555-0175', '919-555-6624', '404-555-0190', '208-555-7410']

In [25]:
# Pandas Native
PHONE_PATTERN = r'\d{3}-\d{3}-\d{4}'

sample_contacts['phone_ok'] = sample_contacts['phone'].str.fullmatch(PHONE_PATTERN, na=False)

print(sample_contacts['phone_ok'].value_counts())

# the rows that need cleaning — far more useful than a list of Match objects
sample_contacts.loc[~sample_contacts['phone_ok'], ['name', 'phone']]

phone_ok
False    12
True      8
Name: count, dtype: int64

               name                phone
1         Bob Marsh       (212) 555-0198
2        Carol Diaz           3125550147
4     Erin Kowalski             555-8891
5         Frank Obi         206.555.7788
6         Grace Lin      +1-503-555-0166
7       Hank Petrov          503-55-0142
9        Jamal Reed         617 555 2200
11  Liam Fitzgerald  phone: 858-555-9021
13   Noah Bergstrom         72-555-01755
15    Pedro Alvarez           919-555-88
17     Rosa Delgado         404/555/0132
19     Tessa Moreau              2085550

In [8]:
'''df.at[row_label, column_label]
This accessor is designed for single-value access using labels, 
without the overhead associated with retrieving larger chunks of data, 
which typically makes it faster than its locator counterpart, loc.
'''
row_index, col_name = (0,'name')
sample_contacts.at[row_index, col_name]

'Alice Nguyen'

In [13]:
# Named groups and Negative lookahead
pattern = r'(?P<user>[\w.+-]+)@(?!example\.com)(?P<domain>[\w-]+\.[\w.-]+)'
emails = []

for email in sample_contacts['email']:
    matches = re.finditer(pattern, email)
    emails = [f"{m.group('user')}@{m.group('domain')}" for m in matches]

In [14]:
sample_contacts['emails'] = sample_contacts['email'].str.findall(pattern)

In [ ]:
# then explode if you want one row per email
non_example_emails = sample_contacts['emails'].explode().dropna()

In [16]:
non_example_emails

1          (bob.marsh, example.org)
2         (carol_diaz, example.net)
6        (grace.lin, example.co.uk)
9        (jamal.reed, example..com)
10      (kira.sandoval, example.io)
13    (noah.bergstrom, example.gov)
Name: emails, dtype: object

In [17]:
sample_contacts

,name,phone,email,emails
0,Alice Nguyen,415-555-4242,alice.nguyen@example.com,[]
1,Bob Marsh,(212) 555-0198,bob.marsh@example.org,"[(bob.marsh, example.org)]"
2,Carol Diaz,3125550147,carol_diaz@example.net,"[(carol_diaz, example.net)]"
3,Dan Whitfield,415-555-1234,dan.whitfield@example,[]
4,Erin Kowalski,555-8891,erin.kowalski@example.com,[]
5,Frank Obi,206.555.7788,frank.obi@@example.com,[]
6,Grace Lin,+1-503-555-0166,grace.lin@example.co.uk,"[(grace.lin, example.co.uk)]"
7,Hank Petrov,503-55-0142,hankpetrov.example.com,[]
8,Iris Calloway,617-555-3311,iris.calloway@example.com,[]
9,Jamal Reed,617 555 2200,jamal.reed@example..com,"[(jamal.reed, example..com)]"
10,Kira Sandoval,858-555-0113,kira.sandoval@example.io,"[(kira.sandoval, example.io)]"
11,Liam Fitzgerald,phone: 858-555-9021,@example.com,[]
12,Maya Robinson,720-555-0175,maya.robinson@example.com,[]
13,Noah Bergstrom,72-555-01755,noah.bergstrom@example.gov,"[(noah.bergstrom, example.gov)]"
14,Olivia Tran,919-555-6624,olivia.tran@example.com,[]
15,Pedro Alvarez,919-555-88,pedro alvarez@example.com,[]
16,Quinn Bailey,404-555-0190,quinn.bailey@example.com,[]
17,Rosa Delgado,404/555/0132,rosa.delgado@example.,[]
18,Sam Achterberg,208-555-7410,sam.achterberg@example.com,[]
19,Tessa Moreau,2085550,tessa.moreau@.com,[]