# Data Analyst Skill Development Exercises
## Python Pandas & Databricks Progression Path

### Dataset Overview
We'll be working with two primary datasets from `/Users/courtneysmith/Documents/Projects/DataPractice/data/raw/`:
1. `fake_data.csv` (200 rows) - Personal/professional information
2. `insurance_policies.csv` (5,000 rows) - Insurance policy data

Additionally, there are processed claims datasets in `/Users/courtneysmith/Documents/Projects/DataPractice/data/processed/` including:
- `insurance_claims.csv` (main claims dataset)
- Individual claim type files (auto, home, life, etc.)

---

## Python Pandas Exercises

### Beginner Level: Foundational Data Manipulation

**Exercise 1: Data Loading and Basic Exploration**
- Load both CSV files into Pandas DataFrames
- Use `.info()`, `.describe()`, `.head()`, `.shape` to understand the data
- Identify data types, missing values, and basic statistics
- Practice selecting columns and filtering rows

**Exercise 2: Data Cleaning Fundamentals**
- Handle missing values using `.isnull()`, `.fillna()`, `.dropna()`
- Convert data types (e.g., strings to datetime, objects to category)
- Remove duplicates using `.duplicated()` and `.drop_duplicates()`
- Standardize text data (case conversion, trimming whitespace)

**Exercise 3: Basic Aggregation and Grouping**
- Use `.groupby()` to calculate summary statistics
- Practice aggregation functions: `.mean()`, `.sum()`, `.count()`, `.std()`
- Create pivot tables using `.pivot_table()`
- Sort data using `.sort_values()`

### Intermediate Level: Advanced Data Transformation

**Exercise 4: String Manipulation and Pattern Extraction**
- Use `.str` accessor for string operations (`.str.contains()`, `.str.split()`, `.str.extract()`)
- Extract structured data from unstructured text fields
- Clean and standardize address/job title fields from fake_data.csv
- Parse email domains and job categories

**Exercise 5: DateTime Operations and Time-Based Analysis**
- Convert date columns to datetime using `pd.to_datetime()`
- Extract datetime components (year, month, day, weekday)
- Calculate time differences and durations
- Resample time series data (if applicable)
- Analyze policy start/end date patterns in insurance data

**Exercise 6: Data Merging and Joining**
- Practice different types of joins: `.merge()` (inner, left, right, outer)
- Combine related datasets (e.g., join insurance policies with claims data)
- Handle duplicate keys and suffixes in merged data
- Use `.concat()` for stacking datasets vertically/horizontally

### Advanced Level: Complex Analytics and Optimization

**Exercise 7: Advanced Grouping and Window Functions**
- Use `.groupby()` with multiple aggregation functions via `.agg()`
- Apply custom aggregation functions
- Implement rolling windows and expanding windows using `.rolling()` and `.expanding()`
- Calculate running totals, moving averages, and cumulative statistics
- Use `.transform()` for group-wise operations

**Exercise 8: Performance Optimization with Large Datasets**
- Optimize memory usage with appropriate data types (`category`, `int32` vs `int64`)
- Use `.query()` for efficient filtering
- Implement chunk processing for very large datasets
- Profile code performance using `%timeit` and memory profiling
- Compare performance of different approaches (loops vs vectorization)

**Exercise 9: Complex Data Pipelines and Automation**
- Build end-to-end data processing pipelines
- Create reusable functions for common data cleaning tasks
- Implement data validation checks and quality scoring
- Export processed data in multiple formats (CSV, Excel, Parquet, JSON)
- Create automated reports with summary statistics and visualizations

---

## Databricks Exercises

### Beginner Level: Getting Started with Databricks

**Exercise 1: Workspace Navigation and Basic Operations**
- Create a new Databricks notebook
- Upload the CSV files to Databricks File System (DBFS)
- Use Spark SQL or PySpark to load data into DataFrames
- Display basic DataFrame information using `.show()`, `.printSchema()`, `.describe()`
- Run simple SQL queries on temporary views

**Exercise 2: Basic Data Transformations in Spark**
- Practice selecting columns with `.select()` and `.selectExpr()`
- Filter data using `.filter()` or `.where()`
- Add new columns using `.withColumn()`
- Rename columns using `.withColumnRenamed()`
- Remove duplicates using `.dropDuplicates()`

**Exercise 3: Introduction to Spark SQL**
- Create temporary views using `.createOrReplaceTempView()`
- Write SQL queries using `%sql` magic
- Practice SQL aggregations: GROUP BY, HAVING, ORDER BY
- Use built-in functions: `count()`, `sum()`, `avg()`, `min()`, `max()`
- Join tables using SQL JOIN syntax

### Intermediate Level: Spark Optimization and Advanced Transformations

**Exercise 4: Working with Different Data Sources**
- Read data from various formats: CSV, JSON, Parquet, Delta Lake
- Write data back to storage in different formats
- Understand partitioning and its impact on performance
- Use Delta Lake for ACID transactions and time travel
- Work with streaming data (basic concepts)

**Exercise 5: Advanced DataFrame Operations**
- Use complex expressions with `.expr()` and SQL functions
- Implement conditional logic using `when()` and `otherwise()`
- Work with nested data structures (arrays, maps, structs)
- Use window functions for advanced analytics
- Implement user-defined functions (UDFs) when necessary

**Exercise 6: Performance Tuning and Caching**
- Understand Spark execution model and DAG optimization
- Use `.cache()` and `.persist()` strategically
- Monitor job performance using Spark UI
- Adjust partitioning for better parallelism
- Broadcast joins for small lookup tables

### Advanced Level: Enterprise-Scale Data Engineering

**Exercise 7: Building ETL Pipelines with Delta Lake**
- Create robust ETL pipelines using Delta Lake
- Implement incremental loading patterns
- Handle schema evolution and data quality checks
- Use Delta Lake transaction logs for audit trails
- Implement slowly changing dimensions (SCD) patterns

**Exercise 8: Machine Learning Integration**
- Prepare features for machine learning models
- Use MLlib for basic machine learning algorithms
- Create feature pipelines using Spark ML
- Split data into training/test sets
- Evaluate model performance using appropriate metrics

**Exercise 9: Production-Ready Databricks Practices**
- Implement proper error handling and logging
- Use notebook workflows and job scheduling
- Implement version control with Git integration
- Optimize costs through autoscaling and spot instances
- Implement security best practices (secrets management, access controls)

---

## Integrated Practice: Combining Pandas and Databricks Skills

**Capstone Project: Insurance Analytics Dashboard**
1. **Data Ingestion**: Load insurance policies and claims data into both Pandas and Spark DataFrames
2. **Data Cleaning**: Standardize formats, handle missing values, validate business rules
3. **Feature Engineering**: Create risk scores, policy longevity metrics, claim frequency indicators
4. **Analytical Processing**:
   - Pandas: Cohort analysis, detailed segmentations, custom aggregations
   - Databricks: Large-scale aggregations, window functions for trend analysis
5. **Optimization**: Compare performance between Pandas (for subsets) and Spark (for full dataset)
6. **Reporting**: Generate executive summary with key metrics and visualizations
7. **Automation**: Create a reproducible pipeline that can refresh with new data

**Learning Progression Tips:**
1. Start with small subsets in Pandas to understand the data structure
2. Scale up to full datasets in Databricks to experience distributed computing
3. Validate results between Pandas and Spark implementations
4. Focus on understanding when to use each tool (Pandas for exploration/modeling, Spark for big data processing)
5. Practice explaining your approach and business insights, not just technical implementation

---

## Resources for Continued Learning

**Python Pandas:**
- Official Pandas documentation: https://pandas.pydata.org/docs/
- "Python for Data Analysis" by Wes McKinney
- Kaggle Pandas courses
- Real Python Pandas tutorials

**Databricks:**
- Databricks Academy: https://academy.databricks.com/
- Databricks documentation: https://docs.databricks.com/
- "Learning Spark" by Holden Karau et al.
- Databricks community edition for practice

**Practice Platforms:**
- Kaggle competitions
- DataCamp courses
- LinkedIn Learning paths
- GitHub repositories with real-world datasets

Remember: The key to mastery is consistent practice with real datasets and focusing on solving business problems, not just learning syntax.

In [22]:
#with open('/Users/courtneysmith/Desktop/data_practice_exercises/data_analyst_skill_exercises.md', mode= 'r') as file:
#    data_exercise_markdown = file.read()
#    print(data_exercise_markdown)

In [2]:
import pandas as pd
insclaims_df = pd.read_csv('/Users/courtneysmith/Documents/Projects/DataPractice/data/processed/insurance_claims.csv')
inspolicies_df = pd.read_csv('/Users/courtneysmith/Documents/Projects/DataPractice/data/raw/insurance_policies.csv')

In [12]:
inspolicies_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 39 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   first_name                 5000 non-null   str
 1   last_name                  5000 non-null   str
 2   date_of_birth              5000 non-null   str
 3   age                        5000 non-null   int64
 4   gender                     5000 non-null   str
 5   marital_status             5000 non-null   str
 6   education                  5000 non-null   str
 7   occupation                 5000 non-null   str
 8   annual_income              5000 non-null   float64
 9   credit_score               5000 non-null   int64
 10  email                      5000 non-null   str
 11  phone                      5000 non-null   str
 12  address                    5000 non-null   str
 13  city                       5000 non-null   str
 14  state                      5000 non-null   str
 15  zip_code                   5000 non-null   int64
 16  policy_id                  5000 non-null   str
 17  customer_id                5000 non-null   str
 18  policy_type                5000 non-null   str
 19  policy_status              5000 non-null   str
 20  risk_tier                  5000 non-null   str
 21  coverage_amount            5000 non-null   float64
 22  deductible                 5000 non-null   int64
 23  annual_premium             5000 non-null   float64
 24  monthly_premium            5000 non-null   float64
 25  payment_frequency          5000 non-null   str
 26  policy_start_date          5000 non-null   datetime64[us]
 27  policy_end_date            5000 non-null   datetime64[us]
 28  tenure_years               5000 non-null   float64
 29  acquisition_channel        5000 non-null   str
 30  agent_id                   5000 non-null   str
 31  has_multi_policy_discount  5000 non-null   bool
 32  num_claims                 5000 non-null   int64
 33  total_claims_paid          5000 non-null   float64
 34  last_claim_date            1500 non-null   str
 35  primary_claim_type         1500 non-null   str
 36  has_safe_driver_discount   5000 non-null   bool
 37  nps_score                  5000 non-null   int64
 38  customer_lifetime_value    5000 non-null   float64
dtypes: bool(2), datetime64[us](2), float64(7), int64(6), str(22)
memory usage: 1.4 MB

In [12]:
insclaims_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1951 entries, 0 to 1950
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   claim_id              1951 non-null   str
 1   policy_id             1951 non-null   str
 2   customer_id           1951 non-null   str
 3   policy_type           1951 non-null   str
 4   claim_date            1951 non-null   str
 5   claim_type            1951 non-null   str
 6   claim_amount          1951 non-null   float64
 7   deductible            1951 non-null   float64
 8   amount_paid           1951 non-null   float64
 9   claim_status          1951 non-null   str
 10  incident_description  1951 non-null   str
dtypes: float64(3), str(8)
memory usage: 167.8 KB

In [13]:
inspolicies_df.describe()

,age,annual_income,credit_score,zip_code,coverage_amount,deductible,annual_premium,monthly_premium,tenure_years,num_claims,total_claims_paid,nps_score,customer_lifetime_value
count,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.000000
mean,53.306600,67900.860000,718.077800,50630.586200,4.258032e+05,1832.800000,4872.652358,406.05439,2.536260,0.390200,5.030686e+04,4.966800,43573.332004
std,18.646623,36682.286997,76.353526,28534.805725,6.483736e+05,1739.992723,3913.603324,326.13358,1.444321,0.668755,2.966209e+05,3.172524,41472.941781
min,22.000000,7800.000000,445.000000,514.000000,1.500000e+04,250.000000,189.830000,15.82000,0.000000,0.000000,0.000000e+00,0.000000,791.900000
25%,37.000000,42700.000000,665.000000,26132.250000,9.900000e+04,500.000000,1792.375000,149.36750,1.300000,0.000000,0.000000e+00,2.000000,14533.902500
50%,53.000000,60150.000000,720.000000,51063.500000,2.200000e+05,1000.000000,3591.750000,299.31000,2.600000,0.000000,0.000000e+00,5.000000,30021.710000
75%,69.000000,83200.000000,774.000000,75304.500000,4.842500e+05,2500.000000,7242.615000,603.55500,3.800000,1.000000,0.000000e+00,8.000000,59389.050000
max,86.000000,378400.000000,850.000000,99913.000000,4.976000e+06,5000.000000,27566.230000,2297.19000,5.000000,3.000000,5.727000e+06,10.000000,373857.680000

In [14]:
insclaims_df.describe()

       claim_amount   deductible   amount_paid
count  1.951000e+03  1951.000000  1.951000e+03
mean   1.391304e+05  1766.401845  1.289258e+05
std    3.849012e+05  1731.714008  3.755317e+05
min    5.000000e+02   250.000000  0.000000e+00
25%    3.124600e+03   500.000000  4.515050e+02
50%    8.696290e+03  1000.000000  5.535310e+03
75%    2.797535e+04  2500.000000  2.212235e+04
max    1.982000e+06  5000.000000  1.982000e+06

In [15]:
inspolicies_df.head()

,first_name,last_name,date_of_birth,age,gender,marital_status,education,occupation,annual_income,credit_score,...,acquisition_channel,agent_id,has_multi_policy_discount,num_claims,total_claims_paid,last_claim_date,primary_claim_type,has_safe_driver_discount,nps_score,customer_lifetime_value
0,Joshua,Walker,1941-12-14,84,F,Single,Bachelor,"Civil engineer, consulting",131900.0,781,...,Phone,AGT-1114,True,0,0.0,NaN,NaN,False,2,73517.99
1,Teresa,Gray,1974-09-02,51,M,Single,Doctorate,Sub,42100.0,548,...,Online,AGT-1016,False,0,0.0,NaN,NaN,True,0,17627.76
2,Nancy,Edwards,2000-09-12,25,M,Single,Some College,Restaurant manager,69300.0,669,...,Agent,AGT-1258,True,0,0.0,NaN,NaN,False,0,5652.89
3,Joseph,Davidson,1974-09-20,51,F,Married,Doctorate,Clinical research associate,86600.0,733,...,Agent,AGT-1112,True,0,0.0,NaN,NaN,False,9,15312.46
4,Sarah,Campos,2002-01-26,24,M,Divorced,High School,"Engineer, control and instrumentation",100300.0,794,...,Agent,AGT-1357,True,0,0.0,NaN,NaN,False,5,23403.52

In [16]:
insclaims_df.head()

,claim_id,policy_id,customer_id,policy_type,claim_date,claim_type,claim_amount,deductible,amount_paid,claim_status,incident_description
0,CLM-100001,POL-1001501,CUST-501501,Renters,2025-12-25,Theft,500.00,1000.0,0.00,Paid,"Apartment burglary; laptop, tablet, and gaming..."
1,CLM-100002,POL-1002586,CUST-502586,Home,2025-05-28,Water Damage,5917.80,2500.0,3417.80,Paid,Burst pipe in the upstairs bathroom flooded th...
2,CLM-100003,POL-1002653,CUST-502653,Auto,2023-09-19,Collision,14417.68,1000.0,0.00,Denied,Rear-end collision at a traffic intersection.
3,CLM-100004,POL-1002653,CUST-502653,Auto,2024-05-07,Uninsured Motorist,3644.21,1000.0,2644.21,Paid,Rear-ended by an uninsured driver who fled the...
4,CLM-100005,POL-1001055,CUST-501055,Auto,2022-01-27,Collision,4512.58,1000.0,3512.58,Paid,Collided with a stationary utility pole while ...

In [3]:
# .shape return rows and columns 
inspolicies_df.shape

(5000, 39)

In [18]:
insclaims_df.shape

(1951, 11)

In [24]:
inspolicies_df[inspolicies_df.num_claims > 0]

,first_name,last_name,date_of_birth,age,gender,marital_status,education,occupation,annual_income,credit_score,...,acquisition_channel,agent_id,has_multi_policy_discount,num_claims,total_claims_paid,last_claim_date,primary_claim_type,has_safe_driver_discount,nps_score,customer_lifetime_value
8,Cheryl,Archer,1985-05-18,41,M,Divorced,Doctorate,Seismic interpreter,153800.0,733,...,Mobile App,AGT-1360,True,2,5535.31,2026-04-23,Comprehensive,True,0,15713.81
12,Zachary,Schultz,1945-10-12,80,F,Single,Doctorate,Legal executive,67900.0,747,...,Agent,AGT-1273,False,1,0.00,2022-11-02,Liability,False,2,43638.70
14,Brandy,Dominguez,1998-04-06,28,F,Single,Bachelor,Teaching laboratory technician,60300.0,836,...,Agent,AGT-1137,False,1,9222.01,2024-01-15,Liability,True,3,44252.38
17,Lindsey,Medina,1957-08-21,68,F,Widowed,Doctorate,Radio broadcast assistant,67200.0,734,...,Agent,AGT-1185,False,1,3588.07,2025-10-19,Water Damage,False,3,4031.89
19,Jeremy,White,1952-10-10,73,M,Married,Some College,"Administrator, education",43000.0,788,...,Agent,AGT-1305,False,1,6196.29,2022-10-26,Liability,False,1,96853.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990,Tyler,Thompson,1958-04-15,68,F,Divorced,Bachelor,Camera operator,110100.0,677,...,Online,AGT-1244,True,1,0.00,2024-11-20,Collision,False,7,25441.15
4995,Richard,Jackson,1995-05-22,30,F,Divorced,Master,Commercial/residential surveyor,82100.0,723,...,Online,AGT-1298,True,1,0.00,2025-08-14,Water Damage,False,9,9252.47
4996,John,Jones,1953-12-23,72,F,Married,Doctorate,Town planner,59500.0,781,...,Online,AGT-1444,True,1,3118.31,2023-08-04,Collision,False,5,42481.01
4998,Pamela,Hernandez,1976-05-15,50,F,Widowed,High School,Claims inspector/assessor,52900.0,628,...,Online,AGT-1446,False,1,19719.43,2025-04-26,Uninsured Motorist,True,10,35206.38
4999,Donna,Adams,1979-07-30,46,F,Single,High School,Chartered public finance accountant,138500.0,766,...,Online,AGT-1094,False,1,0.00,2022-03-04,Water Damage,False,4,5737.53

In [27]:
insclaims_df.claim_type

0                    Theft
1             Water Damage
2                Collision
3       Uninsured Motorist
4                Collision
               ...
1946         Death Benefit
1947                 Theft
1948    Uninsured Motorist
1949             Liability
1950             Liability
Name: claim_type, Length: 1951, dtype: str

In [ ]:
# runs on a dataframe and checks to see what data has null fields 
inspolicies_df.isnull()

,first_name,last_name,date_of_birth,age,gender,marital_status,education,occupation,annual_income,credit_score,...,acquisition_channel,agent_id,has_multi_policy_discount,num_claims,total_claims_paid,last_claim_date,primary_claim_type,has_safe_driver_discount,nps_score,customer_lifetime_value
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
4998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
insclaims_df.isnull()

,claim_id,policy_id,customer_id,policy_type,claim_date,claim_type,claim_amount,deductible,amount_paid,claim_status,incident_description
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1946,False,False,False,False,False,False,False,False,False,False,False
1947,False,False,False,False,False,False,False,False,False,False,False
1948,False,False,False,False,False,False,False,False,False,False,False
1949,False,False,False,False,False,False,False,False,False,False,False
1950,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
# used to replace missing values like NaN in a Series or DataFrame with something else. 
# It returns a new object by default, unless you set inplace=True
inspolicies_df.fillna()

In [6]:
# removes missing values instead of filling them. 
# By default, on a DataFrame it drops rows that contain any missing value, and it returns a new DataFrame unless you set inplace=True
no_nas = inspolicies_df.dropna()
no_nas

,first_name,last_name,date_of_birth,age,gender,marital_status,education,occupation,annual_income,credit_score,...,acquisition_channel,agent_id,has_multi_policy_discount,num_claims,total_claims_paid,last_claim_date,primary_claim_type,has_safe_driver_discount,nps_score,customer_lifetime_value
8,Cheryl,Archer,1985-05-18,41,M,Divorced,Doctorate,Seismic interpreter,153800.0,733,...,Mobile App,AGT-1360,True,2,5535.31,2026-04-23,Comprehensive,True,0,15713.81
12,Zachary,Schultz,1945-10-12,80,F,Single,Doctorate,Legal executive,67900.0,747,...,Agent,AGT-1273,False,1,0.00,2022-11-02,Liability,False,2,43638.70
14,Brandy,Dominguez,1998-04-06,28,F,Single,Bachelor,Teaching laboratory technician,60300.0,836,...,Agent,AGT-1137,False,1,9222.01,2024-01-15,Liability,True,3,44252.38
17,Lindsey,Medina,1957-08-21,68,F,Widowed,Doctorate,Radio broadcast assistant,67200.0,734,...,Agent,AGT-1185,False,1,3588.07,2025-10-19,Water Damage,False,3,4031.89
19,Jeremy,White,1952-10-10,73,M,Married,Some College,"Administrator, education",43000.0,788,...,Agent,AGT-1305,False,1,6196.29,2022-10-26,Liability,False,1,96853.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990,Tyler,Thompson,1958-04-15,68,F,Divorced,Bachelor,Camera operator,110100.0,677,...,Online,AGT-1244,True,1,0.00,2024-11-20,Collision,False,7,25441.15
4995,Richard,Jackson,1995-05-22,30,F,Divorced,Master,Commercial/residential surveyor,82100.0,723,...,Online,AGT-1298,True,1,0.00,2025-08-14,Water Damage,False,9,9252.47
4996,John,Jones,1953-12-23,72,F,Married,Doctorate,Town planner,59500.0,781,...,Online,AGT-1444,True,1,3118.31,2023-08-04,Collision,False,5,42481.01
4998,Pamela,Hernandez,1976-05-15,50,F,Widowed,High School,Claims inspector/assessor,52900.0,628,...,Online,AGT-1446,False,1,19719.43,2025-04-26,Uninsured Motorist,True,10,35206.38
4999,Donna,Adams,1979-07-30,46,F,Single,High School,Chartered public finance accountant,138500.0,766,...,Online,AGT-1094,False,1,0.00,2022-03-04,Water Damage,False,4,5737.53

In [9]:
inspolicies_df['policy_start_date'] = pd.to_datetime(inspolicies_df["policy_start_date"], format = "%Y-%m-%d")
inspolicies_df['policy_start_date']

0      2024-07-19
1      2024-12-31
2      2022-09-09
3      2024-10-04
4      2023-12-28
          ...
4995   2025-07-24
4996   2023-08-02
4997   2023-01-11
4998   2025-02-15
4999   2021-06-14
Name: policy_start_date, Length: 5000, dtype: datetime64[us]

In [11]:
inspolicies_df['policy_end_date'] = pd.to_datetime(inspolicies_df["policy_end_date"], format = "%Y-%m-%d")
inspolicies_df['policy_end_date']

0      2025-07-19
1      2025-12-31
2      2025-12-17
3      2027-10-04
4      2026-02-27
          ...
4995   2025-12-15
4996   2024-08-01
4997   2024-01-11
4998   2028-02-15
4999   2022-06-14
Name: policy_end_date, Length: 5000, dtype: datetime64[us]

In [16]:
inspolicies_df['last_claim_date'] = pd.to_datetime(inspolicies_df["last_claim_date"], format = "%Y-%m-%d")
inspolicies_df['last_claim_date']

0             NaT
1             NaT
2             NaT
3             NaT
4             NaT
          ...
4995   2025-08-14
4996   2023-08-04
4997          NaT
4998   2025-04-26
4999   2022-03-04
Name: last_claim_date, Length: 5000, dtype: datetime64[us]

In [20]:
inspolicies_df.drop(columns='plast_claim_date',inplace= True)

In [24]:
# marks rows or values that have already appeared before. It returns a boolean Series, where True means “this is a duplicate.”
insclaims_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1946    False
1947    False
1948    False
1949    False
1950    False
Length: 1951, dtype: bool

In [23]:
inspolicies_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [25]:
inspolicies_df[inspolicies_df.duplicated()]

Empty DataFrame
Columns: [first_name, last_name, date_of_birth, age, gender, marital_status, education, occupation, annual_income, credit_score, email, phone, address, city, state, zip_code, policy_id, customer_id, policy_type, policy_status, risk_tier, coverage_amount, deductible, annual_premium, monthly_premium, payment_frequency, policy_start_date, policy_end_date, tenure_years, acquisition_channel, agent_id, has_multi_policy_discount, num_claims, total_claims_paid, last_claim_date, primary_claim_type, has_safe_driver_discount, nps_score, customer_lifetime_value]
Index: []

[0 rows x 39 columns]

In [27]:
insclaims_df['claim_date'] = pd.to_datetime(insclaims_df['claim_date'], format="%Y-%m-%d")
insclaims_df['claim_date']

0      2025-12-25
1      2025-05-28
2      2023-09-19
3      2024-05-07
4      2022-01-27
          ...
1946   2023-02-13
1947   2025-07-12
1948   2026-02-06
1949   2026-04-25
1950   2025-08-10
Name: claim_date, Length: 1951, dtype: datetime64[us]

In [28]:
insclaims_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1951 entries, 0 to 1950
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   claim_id              1951 non-null   str
 1   policy_id             1951 non-null   str
 2   customer_id           1951 non-null   str
 3   policy_type           1951 non-null   str
 4   claim_date            1951 non-null   datetime64[us]
 5   claim_type            1951 non-null   str
 6   claim_amount          1951 non-null   float64
 7   deductible            1951 non-null   float64
 8   amount_paid           1951 non-null   float64
 9   claim_status          1951 non-null   str
 10  incident_description  1951 non-null   str
dtypes: datetime64[us](1), float64(3), str(7)
memory usage: 167.8 KB

In [ ]:
insclaims_df['amount_paid'].mean()

np.float64(128925.82511019989)

In [34]:
insclaims_df['claim_amount'].mean()

np.float64(139130.39533059968)

In [38]:
insclaims_df.groupby(by='claim_type')['amount_paid'].mean()

claim_type
Collision               6165.045789
Comprehensive           5573.402750
Death Benefit         958953.191489
Fire                   13669.240828
Liability              32013.177543
Storm Damage            9936.002500
Theft                  12792.863067
Uninsured Motorist      6070.728932
Water Damage           15491.480955
Wind/Hail              19872.806337
Name: amount_paid, dtype: float64

In [40]:
insclaims_df[insclaims_df.policy_type == 'Home']

,claim_id,policy_id,customer_id,policy_type,claim_date,claim_type,claim_amount,deductible,amount_paid,claim_status,incident_description
1,CLM-100002,POL-1002586,CUST-502586,Home,2025-05-28,Water Damage,5917.80,2500.0,3417.80,Paid,Burst pipe in the upstairs bathroom flooded th...
5,CLM-100006,POL-1000705,CUST-500705,Home,2024-04-04,Liability,13557.15,1000.0,12557.15,Paid,Guest tripped over a loose rug and fractured t...
6,CLM-100007,POL-1000106,CUST-500106,Home,2025-06-18,Liability,8695.57,250.0,8445.57,Paid,Mail carrier slipped on icy front steps and sp...
7,CLM-100008,POL-1000589,CUST-500589,Home,2025-08-18,Liability,22738.61,1000.0,21738.61,Paid,Family dog bit a neighbor visiting the backyard.
10,CLM-100012,POL-1001600,CUST-501600,Home,2023-09-12,Fire,28338.93,5000.0,23338.93,Paid,Grease fire in the kitchen caused severe cabin...
...,...,...,...,...,...,...,...,...,...,...,...
1942,CLM-101944,POL-1000321,CUST-500321,Home,2022-02-28,Liability,13476.12,1000.0,12476.12,Paid,Guest tripped over a loose rug and fractured t...
1943,CLM-101945,POL-1000321,CUST-500321,Home,2022-05-16,Wind/Hail,19102.50,1000.0,18102.50,Paid,Fallen tree limb damaged the backyard deck dur...
1944,CLM-101943,POL-1000321,CUST-500321,Home,2022-06-14,Theft,30346.16,1000.0,29346.16,Paid,Break-in through rear window; jewelry and elec...
1945,CLM-101946,POL-1003563,CUST-503563,Home,2022-05-18,Liability,1588.32,250.0,1338.32,Paid,Guest tripped over a loose rug and fractured t...
1947,CLM-101948,POL-1001837,CUST-501837,Home,2025-07-12,Theft,9232.63,250.0,8982.63,Paid,Lawnmower and power tools stolen from locked b...